version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    docker:
      - image: 'circleci/python:latest'

    steps:
      - checkout
      - aws-s3/sync:
          from: .
          to: 's3://www.mahmoudimus.com.s3-website-us-east-1.amazonaws.com'
          aws-region: "us-east-1"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --exclude ".git/*" \
            --exclude ".gitignore" \
            --exclude ".circleci/*" \
          overwrite: true
